name: 'Synchronize Ant Design Styles'
description: 'Synchronize the styles of Ant Design for NG-ZORRO'
inputs:
  account_token:
    description: "The token of the syncer's account"
    default: 'Invalid token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
